import api from "@/components/api";
import { mastersProps } from "../../../TypesStore";

export const getAllPlantData = async (url: string) => {
  const response = await api.get(url.trim());
  return response.data;
};
export const MasterSubFieldWithData: mastersProps = {
  Plant: {
    Plant: {
      getAll: "/plant/getAllPlant",
      getSingle: "/plant/getPlantById",
      create: "/plant/savePlant",
      createBulk: "/plant/ImportExcelDataPlant",
      updateStatus: "/plant/updatePlantStatusById",
      updateBulkStatus: "/plant/updateBulkStatusPlantId",
      template: "/plant/exportTemplatePlant",
      exportPdf: "/plant/pdfPlantReport",
      exportExcel: "/plant/exportDataPlant",
      delete: "/plant/deletePlant",
      deleteBulk: "/plant/deleteBatchPlant",
      update: "/plant/updatePlant",
      includePlantDropdown: false,
    },
    ProfitCenter: {
      getAll: "/plant/getAllProfitCenter",
      getSingle: "/plant/getProfitCenterById",
      create: "/plant/saveProfitCenter",
      createBulk: "/plant/ImportExcelDataProfit",
      updateStatus: "/plant/updateProfitCenterStatusById",
      updateBulkStatus: "/plant/updateBulkStatusProfitCentertId",
      template: "/plant/exportTemplateProfit",
      exportPdf: "/plant/pdfProfitCenterReport",
      exportExcel: "/plant/exportDataProfit",
      delete: "/plant/deleteProfitCenter",
      deleteBulk: "/plant/deleteBatchProfitCenter",
      update: "/plant/updateProfitCenter",
      includePlantDropdown: true,
    },
    PriceControl: {
      getAll: "/plant/getAllPriceControl",
      getSingle: "/plant/getPriceControlById",
      create: "/plant/savePriceControl",
      createBulk: "/plant/ImportExcelDataPrice",
      updateStatus: "/plant/updatePriceControlById",
      updateBulkStatus: "/plant/updateBulkStatusPriceControlId",
      template: "/plant/exportTemplatePrice",
      exportPdf: "/plant/pdfPriceControlReport",
      exportExcel: "/plant/exportDataPrice",
      delete: "/plant/deletePriceControl",
      deleteBulk: "/plant/deleteBatchPriceControl",
      update: "/plant/updatePriceControl",
      includePlantDropdown: false,
    },

    StorageLocation: {
      getAll: "/plant/getAllStorageLocation",
      getSingle: "/plant/getStorageLocationById",
      create: "/plant/saveStorageLocation",
      createBulk: "/plant/ImportExcelDataStorageLocation",
      updateStatus: "/plant/updateStorageLocationStatusById1",
      updateBulkStatus: "/plant/updateBulkStorageLocationId1",
      template: "/plant/exportTemplateStorageLocation",
      exportPdf: "/plant/pdfStorageLocationReport",
      exportExcel: "/plant/exportDataStorageLocation",
      delete: "/plant/deleteStorageLocation",
      deleteBulk: "/plant/deleteBatchStorageLocation",
      update: "/plant/updateStorageLocation",
      includePlantDropdown: true,
    },
    StorageBin: {
      getAll: "/plant/getAllStorageLocationBin",
      getSingle: "/plant/getStorageLocationBinById",
      create: "/plant/saveStorageLocationBin",
      createBulk: "/plant/ImportExcelDataStorageBin",
      updateStatus: "/plant/updateStorageLocationStatusById",
      updateBulkStatus: "/plant/updateBulkStorageLocationId",
      template: "/plant/exportTemplateStorageLocationBin",
      exportPdf: "/plant/pdfStorageBinReport",
      exportExcel: "/plant/exportDataStorageLocationBin",
      delete: "/plant/deleteStorageLocationBin",
      deleteBulk: "/plant/deleteBatchStorageLocationBin",
      update: "/plant/updateStorageLocationBin",
      includePlantDropdown: false,
    },
    ValuationCategory: {
      getAll: "/plant/getAllValuationCategory",
      getSingle: "/plant/getValuationCategoryById",
      create: "/plant/saveValuationCategory",
      createBulk: "/plant/ImportExcelDataValuationCategory",
      updateStatus: "/plant/updateValuationCategoryById",
      updateBulkStatus: "/plant/updateBulkStatusValuationCategoryId",
      template: "/plant/exportTemplateValuationCategory",
      exportPdf: "/plant/pdfValuationCategoryReport",
      exportExcel: "/plant/exportDataValuationCategory",
      delete: "/plant/deleteValuationCategory",
      deleteBulk: "/plant/deleteBatchValuationCategory",
      update: "/plant/updateValuationCategory",
      includePlantDropdown: false,
    },
    VarianceKey: {
      getAll: "/plant/getAllVarianceKey",
      getSingle: "/plant/getVarianceKeyById",
      create: "/plant/saveVarianceKey",
      createBulk: "/plant/ImportExcelDataVarianceKey",
      updateStatus: "/plant/updateVarianceKeyById",
      updateBulkStatus: "/plant/updateBulkStatusVarianceKeyId",
      template: "/plant/exportTemplateVarianceKey",
      exportPdf: "/plant/pdfVarianceKeyReport",
      exportExcel: "/plant/exportDataVarianceKey",
      delete: "/plant/deleteVarianceKey",
      deleteBulk: "/plant/deleteVarianceKey",
      update: "/plant/updateVarianceKey",
      includePlantDropdown: false,
    },
    ValuationClass: {
      getAll: "/plant/getAllValuationClass?showFull=false",
      getSingle: "/plant/getValuationClassById",
      create: "/plant/saveValuationClass",
      createBulk: "/plant/ImportExcelDataValuationClass",
      updateStatus: "/plant/updateValuationClassById",
      updateBulkStatus: "/plant/updateBulkStatusValuationClassId",
      template: "/plant/exportTemplateValuationClass",
      exportPdf: "/plant/pdfValuationClassReport",
      exportExcel: "/plant/exportDataValuationClass",
      delete: "/plant/deleteValuationClass",
      deleteBulk: "/plant/deleteBatchPriceControl",
      update: "/plant/updateValuationClass",
      includePlantDropdown: false,
    },

    Department: {
      getAll: "/plant/getAllDepartment",
      getSingle: "/plant/getDepartmentById",
      create: "/plant/saveDepartment",
      createBulk: "/plant/ImportExcelDataDepartment",
      updateStatus: "/plant/updateDepartmentStatusById",
      updateBulkStatus: "/plant/updateBulkStatusDepartmentId",
      template: "/plant/exportTemplateDept",
      exportPdf: "/plant/pdfDepartmentReport",
      exportExcel: "/plant/exportDataDept",
      delete: "/plant/deleteDepartment",
      deleteBulk: "/plant/deleteBatchDepartment",
      update: "/plant/updateDepartment",
      includePlantDropdown: false,
    },
  },
  General: {
    IndustrySector: {
      getAll: "/general/getAllSector",
      getSingle: "/general/getSectorById",
      create: "/general/saveSector",
      createBulk: "",
      updateStatus: "/general/updateSectorStatus",
      updateBulkStatus: "/general/updateBatchSectorStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteSector",
      deleteBulk: "/general/deleteBatchSector",
      update: "/general/updateSector",
      includePlantDropdown: false,
      keyName: "sector",
    },
    MaterialType: {
      getAll: "/general/getAllMaterial",
      getSingle: "/general/getMaterialById",
      create: "/general/saveMaterial",
      createBulk: "",
      updateStatus: "/general/updateMaterialStatus",
      updateBulkStatus: "/general/updateBatchMaterialStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteMaterial",
      deleteBulk: "/general/deleteBatchMaterial",
      update: "/general/updateMaterial",
      includePlantDropdown: false,
      keyName: "material",
    },
    BaseUOP: {
      getAll: "/general/getAllUop",
      getSingle: "/general/getUopById",
      create: "/general/saveUop",
      createBulk: "",
      updateStatus: "/general/updateUopStatus",
      updateBulkStatus: "/general/updateBatchUopStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteUop",
      deleteBulk: "/general/deleteBatchUop",
      update: "/general/updateUop",
      includePlantDropdown: false,
      keyName: "uop",
    },

    UnitOfIssue: {
      getAll: "/general/getAllUOI",
      getSingle: "/general/getUOIById",
      create: "/general/saveUOI",
      createBulk: "",
      updateStatus: "/general/updateUOIStatus",
      updateBulkStatus: "/general/updateBatchUOIStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteUOI",
      deleteBulk: "/general/deleteBatchUOI",
      update: "/general/updateUOI",
      includePlantDropdown: false,
      keyName: "uoi",
    },
    AlternateUOM: {
      getAll: "/general/getAllUom",
      getSingle: "/general/getUomById",
      create: "/general/saveUom",
      createBulk: "",
      updateStatus: "/general/updateUomStatus",
      updateBulkStatus: "/general/updateBatchUomStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteUom",
      deleteBulk: "/general/deleteBatchUom",
      update: "/general/updateUom",
      includePlantDropdown: false,
      keyName: "uom",
    },
    InspectionType: {
      getAll: "/general/getAllInType",
      getSingle: "/general/getInTypeById",
      create: "/general/saveInType",
      createBulk: "",
      updateStatus: "/general/updateInTypeStatus",
      updateBulkStatus: "/general/updateBatchInTypeStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteInType",
      deleteBulk: "/general/deleteBatchInType",
      update: "/general/updateInType",
      includePlantDropdown: false,
      keyName: "inType",
    },
    InspectionCode: {
      getAll: "/general/getAllInCode",
      getSingle: "/general/getInCodeById",
      create: "/general/saveInCode",
      createBulk: "",
      updateStatus: "/general/updateInCodeStatus",
      updateBulkStatus: "/general/updateBatchInCodeStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteInCode",
      deleteBulk: "/general/deleteBatchInCode",
      update: "/general/updateInCode",
      includePlantDropdown: false,
      keyName: "inCode",
    },
    Division: {
      getAll: "/general/getAllDivision",
      getSingle: "/general/getDivisionById",
      create: "/general/saveDivision",
      createBulk: "",
      updateStatus: "/general/updateDivisionStatus",
      updateBulkStatus: "/general/updateBatchDivisionStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteDivision",
      deleteBulk: "/general/deleteBatchDivision",
      update: "/general/updateDivision",
      includePlantDropdown: false,
      keyName: "div",
    },

    SalesUnit: {
      getAll: "/general/getAllSalesUnit",
      getSingle: "/general/getSalesUnitById",
      create: "/general/saveSalesUnit",
      createBulk: "",
      updateStatus: "/general/updateSalesUnitStatus",
      updateBulkStatus: "/general/updateBatchSalesUnitStatus",
      template: "",
      exportPdf: "",
      exportExcel: "",
      delete: "/general/deleteSalesUnit",
      deleteBulk: "/general/deleteBatchSalesUnit",
      update: "/general/updateSalesUnit",
      includePlantDropdown: false,
      keyName: "sales",
    },
  },
  MRPData: {
    MRPType: {
      getAll: "/general/getAllPlant",
      getSingle: "/general/getPlantById",
      create: "/general/savePlant",
      createBulk: "/general/ImportExcelDataPlant",
      updateStatus: "/plant/updatePlantStatusById",
      updateBulkStatus: "/plant/updateBulkStatusPlantId",
      template: "/plant/exportTemplatePlant",
      exportPdf: "/plant/pdfPlantReport",
      exportExcel: "/plant/exportDataPlant",
      delete: "/plant/deletePlant",
      deleteBulk: "/plant/deleteBatchPlant",
      update: "/plant/updatePlant",
      includePlantDropdown: false,
      keyName: "",
    },
    MRPController: {
      getAll: "/plant/getAllProfitCenter",
      getSingle: "/plant/getProfitCenterById",
      create: "/plant/saveProfitCenter",
      createBulk: "/plant/ImportExcelDataProfit",
      updateStatus: "/plant/updateProfitCenterStatusById",
      updateBulkStatus: "/plant/updateBulkStatusProfitCentertId",
      template: "/plant/exportTemplateProfit",
      exportPdf: "/plant/pdfProfitCenterReport",
      exportExcel: "/plant/exportDataProfit",
      delete: "/plant/deleteProfitCenter",
      deleteBulk: "/plant/deleteBatchProfitCenter",
      update: "/plant/updateProfitCenter",
      includePlantDropdown: true,
      keyName: "",
    },
    LOTSize: {
      getAll: "/plant/getAllPriceControl",
      getSingle: "/plant/getPriceControlById",
      create: "/plant/savePriceControl",
      createBulk: "/plant/ImportExcelDataPrice",
      updateStatus: "/plant/updatePriceControlById",
      updateBulkStatus: "/plant/updateBulkStatusPriceControlId",
      template: "/plant/exportTemplatePrice",
      exportPdf: "/plant/pdfPriceControlReport",
      exportExcel: "/plant/exportDataPrice",
      delete: "/plant/deletePriceControl",
      deleteBulk: "/plant/deleteBatchPriceControl",
      update: "/plant/updatePriceControl",
      includePlantDropdown: false,
      keyName: "",
    },

    ProcurementType: {
      getAll: "/plant/getAllStorageLocation",
      getSingle: "/plant/getStorageLocationById",
      create: "/plant/saveStorageLocation",
      createBulk: "/plant/ImportExcelDataStorageLocation",
      updateStatus: "/plant/updateStorageLocationStatusById1",
      updateBulkStatus: "/plant/updateBulkStorageLocationId1",
      template: "/plant/exportTemplateStorageLocation",
      exportPdf: "/plant/pdfStorageLocationReport",
      exportExcel: "/plant/exportDataStorageLocation",
      delete: "/plant/deleteStorageLocation",
      deleteBulk: "/plant/deleteBatchStorageLocation",
      update: "/plant/updateStorageLocation",
      includePlantDropdown: true,
      keyName: "",
    },
    PlanningStrgyGrp: {
      getAll: "/plant/getAllStorageLocationBin",
      getSingle: "/plant/getStorageLocationBinById",
      create: "/plant/saveStorageLocationBin",
      createBulk: "/plant/ImportExcelDataStorageBin",
      updateStatus: "/plant/updateStorageLocationStatusById",
      updateBulkStatus: "/plant/updateBulkStorageLocationId",
      template: "/plant/exportTemplateStorageLocationBin",
      exportPdf: "/plant/pdfStorageBinReport",
      exportExcel: "/plant/exportDataStorageLocationBin",
      delete: "/plant/deleteStorageLocationBin",
      deleteBulk: "/plant/deleteBatchStorageLocationBin",
      update: "/plant/updateStorageLocationBin",
      includePlantDropdown: false,
      keyName: "",
    },
    AvailableGroup: {
      getAll: "/plant/getAllValuationCategory",
      getSingle: "/plant/getValuationCategoryById",
      create: "/plant/saveValuationCategory",
      createBulk: "/plant/ImportExcelDataValuationCategory",
      updateStatus: "/plant/updateValuationCategoryById",
      updateBulkStatus: "/plant/updateBulkStatusValuationCategoryId",
      template: "/plant/exportTemplateValuationCategory",
      exportPdf: "/plant/pdfValuationCategoryReport",
      exportExcel: "/plant/exportDataValuationCategory",
      delete: "/plant/deleteValuationCategory",
      deleteBulk: "/plant/deleteBatchValuationCategory",
      update: "/plant/updateValuationCategory",
      includePlantDropdown: false,
      keyName: "",
    },
    ScheduleMargin: {
      getAll: "/plant/getAllVarianceKey",
      getSingle: "/plant/getVarianceKeyById",
      create: "/plant/saveVarianceKey",
      createBulk: "/plant/ImportExcelDataVarianceKey",
      updateStatus: "/plant/updateVarianceKeyById",
      updateBulkStatus: "/plant/updateBulkStatusVarianceKeyId",
      template: "/plant/exportTemplateVarianceKey",
      exportPdf: "/plant/pdfVarianceKeyReport",
      exportExcel: "/plant/exportDataVarianceKey",
      delete: "/plant/deleteVarianceKey",
      deleteBulk: "/plant/deleteVarianceKey",
      update: "/plant/updateVarianceKey",
      includePlantDropdown: false,
      keyName: "",
    },
  },
  //General and MAP need to change
};
