export const initialDynamicStateField = {
  fieldName: "",
  dataType: "",
  identity: "",
  min: 2,
  max: 5,
  isRequired: false,
  pattern: [],
  isExtraField: true,
  isReadable: true,
  isWritable: true,
  isUnique: false,
  enums: [],
  dropDowns: [],
  displayRelationFieldName: "",
};
