import { MaterialMasterRootProps } from "../../../TypesStore";

export const MaterialMasteresData: MaterialMasterRootProps = {
  name: "MaterialMaster",
  isField: false,
  isHaveSubForm: true,
  formFields: [
    {
      name: "legacyData",
      isField: true,
      isHaveSubForm: false,
      formFields: [],
      displayName: "Legacy Data",
      view: true,
      modify: true,
    },
    {
      name: "legacySearch",
      isField: true,
      formFields: [],
      displayName: "Legacy Search",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "additionalLegacy",
      isField: true,
      formFields: [],
      displayName: "Additional Legacy",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "noun",
      isField: true,
      formFields: [],
      displayName: "Noun",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "modifier",
      isField: true,
      formFields: [],
      displayName: "Modifier",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "UOM",
      isField: true,
      formFields: [],
      displayName: "UOM",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "itemType",
      isField: true,
      formFields: [],
      displayName: "Item Type",
      isHaveSubForm: false,
      view: true,
      modify: false,
    },
    {
      name: "equipmentDetails",
      isField: false,
      isHaveSubForm: false,
      view: true,
      modify: true,

      displayName: "Equipment Details",
      formFields: [
        {
          name: "equipmentName",
          isField: true,
          formFields: [],
          displayName: "Equipment Name",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
        {
          name: "equipmentModelNo",
          isField: true,
          formFields: [],
          displayName: "Equipment Model No",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
        {
          name: "equipmentMFR",
          isField: true,
          formFields: [],
          displayName: "Equipment MFR",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
        {
          name: "equipmentTagNo",
          isField: true,
          formFields: [],
          displayName: "Equipment Tag No",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
        {
          name: "equipmentInformation",
          isField: true,
          formFields: [],
          displayName: "Equipment Information",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
        {
          name: "equipmentSerialNo",
          isField: true,
          formFields: [],
          displayName: "Equipment Serial No",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
      ],
    },
  ],
};
