import { MaterialMasterRootProps } from "../../../TypesStore";

export const MaterialMasteresData: MaterialMasterRootProps = {
  name: "MaterialMaster",
  isField: false,
  isHaveSubForm: true,
  formFields: [
    {
      name: "sourceDesc",
      isField: true,
      isHaveSubForm: false,
      formFields: [],
      displayName: "Source Desc",
      view: true,
      modify: true,
    },

    {
      name: "noun",
      isField: true,
      formFields: [],
      displayName: "Noun",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "modifier",
      isField: true,
      formFields: [],
      displayName: "Modifier",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "UOM",
      isField: true,
      formFields: [],
      displayName: "UOM",
      isHaveSubForm: false,
      view: true,
      modify: true,
    },
    {
      name: "itemType",
      isField: true,
      formFields: [],
      displayName: "Item Type",
      isHaveSubForm: false,
      view: true,
      modify: false,
    },
    {
      name: "description",
      isField: false,
      displayName: "Description",
      isHaveSubForm: true,
      view: true,
      modify: true,
      formFields: [
        {
          name: "characteristics",
          isField: false,
          displayName: "Characteristics",
          isHaveSubForm: true,
          view: true,
          modify: true,
          formFields: [
            {
              name: "characteristics",
              isField: true,
              formFields: [],
              displayName: "Characteristics",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "shortDesc",
              isField: true,
              formFields: [],
              displayName: "Short Desc",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "longDesc",
              isField: true,
              formFields: [],
              displayName: "Long Desc",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "additionalDataForDesc",
              isField: true,
              formFields: [],
              displayName: "Additional Data For Desc",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "missingValue",
              isField: true,
              formFields: [],
              displayName: "Missing Value",
              isHaveSubForm: false,
              view: true,
              modify: false,
            },
            {
              name: "enrichedValue",
              isField: true,
              formFields: [],
              displayName: "Enriched Value",
              isHaveSubForm: false,
              view: true,
              modify: false,
            },
            {
              name: "repeatedValue",
              isField: true,
              formFields: [],
              displayName: "Repeated Value",
              isHaveSubForm: false,
              view: true,
              modify: false,
            },
          ],
        },
        {
          name: "equipmentDetails",
          isField: false,
          isHaveSubForm: false,
          view: true,
          modify: true,
          displayName: "Equipment Details",
          formFields: [
            {
              name: "equipmentName",
              isField: true,
              formFields: [],
              displayName: "Equipment Name",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "equipmentModelNo",
              isField: true,
              formFields: [],
              displayName: "Equipment Model No",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "equipmentMFR",
              isField: true,
              formFields: [],
              displayName: "Equipment MFR",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "equipmentTagNo",
              isField: true,
              formFields: [],
              displayName: "Equipment Tag No",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "equipmentInformation",
              isField: true,
              formFields: [],
              displayName: "Equipment Information",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
            {
              name: "equipmentSerialNo",
              isField: true,
              formFields: [],
              displayName: "Equipment Serial No",
              isHaveSubForm: false,
              view: true,
              modify: true,
            },
          ],
        },

        {
          name: "vendor",
          isField: false,
          displayName: "Vendor Details",
          isHaveSubForm: true,
          view: true,
          modify: true,
          formFields: [],
        },
      ],
    },
    {
      name: "plant",
      isField: false,
      displayName: "Plant",
      isHaveSubForm: true,
      view: true,
      modify: true,
      formFields: [
        {
          name: "plant",
          isField: true,
          formFields: [],
          displayName: "Plant",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
        {
          name: "priceControl",
          isField: true,
          formFields: [],
          displayName: "Price Control",
          isHaveSubForm: false,
          view: true,
          modify: true,
        },
      ],
    },
    {
      name: "codeLogic",
      isField: false,
      displayName: "Code Logic",
      isHaveSubForm: true,
      view: true,
      modify: true,
      formFields: [],
    },
    {
      name: "attachment",
      isField: false,
      displayName: "Attachment",
      isHaveSubForm: true,
      view: true,
      modify: true,
      formFields: [],
    },
  ],
};
