export const colorThemesArr = [
  {
    id: 1,
    name: "default",
    primaryColor: "#1976d2",
    secondaryColor: "#1669bb",
    tertiaryColor: "#d1e3f6",
  },
  {
    id: 2,
    name: "Dark Red",
    primaryColor: "#CE5A67",
    secondaryColor: "#a04650",
    tertiaryColor: "#FCF5ED",
  },
  {
    id: 3,
    name: "Green",
    primaryColor: "#436850",
    secondaryColor: "#294B3F",
    tertiaryColor: "#f4f7ee",
  },
  {
    id: 4,
    name: "Purple",
    primaryColor: "#535C91",
    secondaryColor: "#262A42",
    tertiaryColor: "#e6e8f1",
  },
  {
    id: 5,
    name: "Brown",
    primaryColor: "#994D1C",
    secondaryColor: "#6B240C",
    tertiaryColor: "#FCF5ED",
  },
  {
    id: 6,
    name: "LotusTheme",
    primaryColor: "#1A1C20",
    secondaryColor: "#EABE6C",
    tertiaryColor: "#fef7dd",
  },
  {
    id: 7,
    name: "Violet",
    primaryColor: "#845EC2",
    secondaryColor: "#04004A",
    tertiaryColor: "#fdf6ff",
  },
];
export const initialFontProperty = [
  {
    id: 1,
    fontFormat: "title",
    fontSize: 14,
    fontWeight: "bold",
  },
  {
    id: 2,
    fontFormat: "subTitle",
    fontSize: 12,
    fontWeight: "600",
  },
  {
    id: 3,
    fontFormat: "body",
    fontSize: 12,
    fontWeight: "normal",
  },
  {
    id: 4,
    fontFormat: "bodySmall",
    fontSize: 10,
    fontWeight: "normal",
  },
];
export const FontsListArr = [
  "Segoe UI",
  "Arial",
  "Calibri",
  "Lucida Sans",
  // "Microsoft Gothic Neo",
  // "Microsoft San Serif",
  // "Source Sans Pro",
  "Tahoma",
  "Verdana",
  // "Univers",
  // "Montserrat",
];
